### ISSUE TITLE
On cmake Every Line Seems Deep Indented

### ISSUE THREAD

**Issue by umitkablan** [dodie/vim-disapprove-deep-indentation#11]
When I open a cmake file every line is shown with a deep indentation conceal.

**Comment by dodie** [comment]
Hi!

I've added a fix to the plugin to play nicely with the default CMake syntax.
It seems that this also fixes the problem with CMakeLists.txt, mentioned by @jorgehatccrma in #2.
Could you verify that the new version is working appropriately?

Thanks!

**Comment by umitkablan** [comment]
it works, thanks!
