### ISSUE TITLE
Needed to call g:DisapproveDeepIndent on vim 7.3

### ISSUE THREAD

**Issue by casssoft** [dodie/vim-disapprove-deep-indentation#4]
Got an error about not being able to find the DisapproveDeepIndent function so I changed it to
call g:DisapproveDeepIndent instead and then it worked. (Also had to update to a version with +conceal)

**Comment by dodie** [comment]
Thanks for the info and the PR! I've changed the call to g:DisapproveDeepIndent as you suggested.
