### ISSUE TITLE
Disable it in vim help file?

### ISSUE THREAD

**Issue by pi314** [dodie/vim-disapprove-deep-indentation#6]
They are like "You already read this page for 5 minutes ಠ_ಠ"

"How much time does it take for you to understand Vim regex? ಠ_ಠ"

**Comment by dodie** [comment]
You are right, it looks stupid. I've changed the plugin to only show the ```ಠ_ಠ``` if the buffer is modifiable.

**Comment by pi314** [comment]
Wow, this way is much better than I thought, I had no idea how many filetypes do I need to disable. Check `modifiable` flag looks reasonable to me.
