### ISSUE TITLE
Question about gif from README

### ISSUE THREAD

**Issue by dominikduda** [dodie/vim-disapprove-deep-indentation#7]
I have question related to the first GIF from readme.

How did u achieve highlighting `if` and `for`?

Is there a plugin for that?

**Comment by dodie** [comment]
I have the following snippet in my .vimrc:

```vim
augroup Highlights
    autocmd!

    " ... other highlighting rules

    "Highlight occurrences of the word under the cursor
    autocmd CursorMoved * exe printf('match IncSearch /\V\<%s\>/', escape(expand('<cword>'), '/\'))
augroup END
```

**Comment by dominikduda** [comment]
Thanks!

I thought though that it works a little bit differently.

I do not understand advanced VIM API, so I have one more question. Would it be possible using a technique similar to above one to highlight matching `do` and `end` or `if` and `end` (same way matching braces are highlighted)?

**Comment by dodie** [comment]
I didn't try, but ruby-matchit.vim seems to provide similar functionality, see [this](http://stackoverflow.com/questions/3413189/vim-highlight-keyword-pairs-in-ruby-def-end-do-end-etc) SO thread for details. It might be a good starting point to create the functionality you described.

**Comment by dominikduda** [comment]
Thanks for the answer!

Please do not close this issue yet. Whenever I will find some free time I will lurk into this and post my research here, so potential people searching for this topic will find a solution.

**Comment by dodie** [comment]
Ok, i'll keep it open for a while.

**Comment by dominikduda** [comment]
Hello!

I created vim_current_word plugin based on script mentioned above.

You can get it [here](https://github.com/dominikduda/vim_current_word).

I mentioned you in credits.

Thanks for help!

**Comment by dodie** [comment]
Nice work!
