### ISSUE TITLE
Too sensitive with python docstring?

### ISSUE THREAD

**Issue by pi314** [dodie/vim-disapprove-deep-indentation#8]
Hi,

I'm writing a python function with docstring, and suddenly `ಠ_ಠ` shows up:
![2017-04-10 20 08 32](https://cloud.githubusercontent.com/assets/826832/24861016/bc19dc04-1e29-11e7-89fc-ed564f6ea715.png)

I checked `:echom g:LookOfDisapprovalSpaceThreshold` and got `40`, and I didn't configure anything about this plugin.

**Comment by dodie** [comment]
Hi!

It seems that the plugin conflicts with the default python syntax rules when it comes to docstrings.
I've added an exception to the plugin that tries to detect and fix the incompatible syn rule.

Could you verify if the new version works appropriately?

Thanks,
David

**Comment by pi314** [comment]
Works great 🎉

Thank you, I really love this plugin 😄

**Comment by dodie** [comment]
I'm glad to hear that! :)
